const bgByType = {
  normal: "bg-gradient-to-t from-rose-800 to-rose-950",
  fighting: "bg-gradient-to-t from-amber-700 to-amber-950",
  flying: "bg-gradient-to-t from-cyan-200 to-cyan-400",
  poison: "bg-gradient-to-t from-purple-500 to-purple-700",
  ground: "bg-gradient-to-t from-orange-700 to-orange-900",
  rock: "bg-gradient-to-t from-stone-400 to-stone-600",
  bug: "bg-gradient-to-t from-emerald-400 to-emerald-600",
  ghost: "bg-gradient-to-t from-indigo-700 to-indigo-900",
  steel: "bg-gradient-to-t from-slate-700 to-slate-900",
  fire: "bg-gradient-to-t from-orange-300 to-orange-500",
  water: "bg-gradient-to-t from-blue-500 to-blue-700",
  grass: "bg-gradient-to-t from-teal-200 to-teal-400",
  electric: "bg-gradient-to-t from-blue-800 to-blue-950",
  psychic: "bg-gradient-to-t from-red-500 to-red-700",
  ice: "bg-gradient-to-t from-sky-200 to-sky-400",
  dragon: "bg-gradient-to-t from-cyan-600 to-cyan-700",
  dark: "bg-gradient-to-t from-neutral-800 to-neutral-950",
  fairy: "bg-gradient-to-t from-pink-600 to-pink-700",
  unknown: "bg-gradient-to-t from-lime-300 to-lime-500",
  shadow: "bg-gradient-to-t from-gray-300 to-gray-500",
};

const borderByType = {
    normal: "border-rose-800",
    fighting: "border-amber-700",
    flying: "border-cyan-300",
    poison: "border-purple-400",
    ground: "border-orange-700",
    rock: "border-stone-400",
    bug: "border-emerald-400",
    ghost: "border-indigo-700",
    steel: "border-slate-700",
    fire: "border-orange-500",
    water: "border-blue-500",
    grass: "border-teal-200",
    electric: "border-blue-800",
    psychic: "border-red-500",
    ice: "border-sky-300",
    dragon: "border-cyan-600",
    dark: "border-neutral-800",
    fairy: "border-pink-600",
    unknown: "border-lime-400",
    shadow: "border-gray-400",
  };

  const textByType = {
    normal: "text-rose-800",
    fighting: "text-amber-700",
    flying: "text-cyan-300",
    poison: "text-purple-400",
    ground: "text-orange-700",
    rock: "text-stone-400",
    bug: "text-emerald-400",
    ghost: "text-indigo-700",
    steel: "text-slate-700",
    fire: "text-orange-500",
    water: "text-blue-500",
    grass: "text-teal-200",
    electric: "text-blue-800",
    psychic: "text-red-500",
    ice: "text-sky-300",
    dragon: "text-cyan-600",
    dark: "text-neutral-800",
    fairy: "text-pink-600",
    unknown: "text-lime-400",
    shadow: "text-gray-400",
  };

export {bgByType, borderByType, textByType}
